/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const SalesLazyImport = createFileRoute('/sales')()
const ProductsLazyImport = createFileRoute('/products')()
const DashboardLazyImport = createFileRoute('/dashboard')()
const CategoryLazyImport = createFileRoute('/category')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const SalesLazyRoute = SalesLazyImport.update({
  path: '/sales',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/sales.lazy').then((d) => d.Route))

const ProductsLazyRoute = ProductsLazyImport.update({
  path: '/products',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/products.lazy').then((d) => d.Route))

const DashboardLazyRoute = DashboardLazyImport.update({
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/dashboard.lazy').then((d) => d.Route))

const CategoryLazyRoute = CategoryLazyImport.update({
  path: '/category',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/category.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/category': {
      preLoaderRoute: typeof CategoryLazyImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      preLoaderRoute: typeof DashboardLazyImport
      parentRoute: typeof rootRoute
    }
    '/products': {
      preLoaderRoute: typeof ProductsLazyImport
      parentRoute: typeof rootRoute
    }
    '/sales': {
      preLoaderRoute: typeof SalesLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  CategoryLazyRoute,
  DashboardLazyRoute,
  ProductsLazyRoute,
  SalesLazyRoute,
])

/* prettier-ignore-end */
