export enum Department {
  Electronics = "Electronics",
  Groceries = "Groceries",
  Clothing = "Clothing",
  Books = "Books",
  Movies = "Movies",
  Music = "Music",
  Games = "Games",
  Sports = "Sports",
  Outdoors = "Outdoors",
  Automotive = "Automotive",
  Industrial = "Industrial",
  Toys = "Toys",
  Beauty = "Beauty",
  Health = "Health",
  Home = "Home",
  Garden = "Garden",
  Tools = "Tools",
  Kids = "Kids",
  Baby = "Baby",
  Shoes = "Shoes",
  Jewelry = "Jewelry",
  Watches = "Watches",
  Pet = "Pet",
  Grocery = "Grocery",
}
