export enum Department {
  Electronics = "Electronics",
  Groceries = "Groceries",
  Clothing = "Clothing",
  Books = "Books",
  Movies = "Movies",
  Music = "Music",
  Games = "Games",
  Sports = "Sports",
  Outdoors = "Outdoors",
  Automotive = "Automotive",
  Industrial = "Industrial",
  Toys = "Toys",
  Beauty = "Beauty",
  Health = "Health",
  Home = "Home",
  Garden = "Garden",
  Tools = "Tools",
  Kids = "Kids",
  Baby = "Baby",
  Shoes = "Shoes",
  Jewelry = "Jewelry",
  Watches = "Watches",
  Pet = "Pet",
  Grocery = "Grocery",
}
export enum ProductNames {
  EcoFriendlyShampoo = "EcoFriendlyShampoo",
  WirelessEarbuds = "WirelessEarbuds",
  OrganicCoffeeBeans = "OrganicCoffeeBeans",
  FitnessTrackerWatch = "FitnessTrackerWatch",
  ErgonomicOfficeChair = "ErgonomicOfficeChair",
  PortableBluetoothSpeaker = "PortableBluetoothSpeaker",
  StainlessSteelWaterBottle = "StainlessSteelWaterBottle",
  VeganLeatherBoots = "VeganLeatherBoots",
  HandmadeWoodenClock = "HandmadeWoodenClock",
  RecycledPlasticSunglasses = "RecycledPlasticSunglasses",
  NaturalBambooToothbrush = "NaturalBambooToothbrush",
  ReusableShoppingBag = "ReusableShoppingBag",
  SolarPoweredCharger = "SolarPoweredCharger",
  BiodegradablePhoneCase = "BiodegradablePhoneCase",
  OrganicCottonTShirt = "OrganicCottonTShirt",
  NonToxicYogaMat = "NonToxicYogaMat",
  FairTradeChocolate = "FairTradeChocolate",
  SustainableWineCorkscrew = "SustainableWineCorkscrew",
  LaundryDetergent = "LaundryDetergent",
  RecycledPaperNotebook = "RecycledPaperNotebook",
}
